name: Myfirst workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options: [info, warning, debug]
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        required: true
jobs:
    first_job:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [hello-world, alpine]
                exclude:
                    - os: windows-latest
                     images: [hello-world, alpine]
        runs-on: ${{matrix.os}}
        steps:
            - name: checkout
              uses: actions/checkout@v7
            - name: see data
              run: |
                ls
                echo ${{vars.REPO_OWNER}}--- ${{secrets.ACCESS_TOKEN}}
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: see
              run: pwd

